from .Clientes import Cliente as ClienteResource
from .Clientes import Clientes as ClientesResource
from .Usuarios import Usuarios as UsuariosResource
from .Usuarios import Usuario as UsuarioResource
from .Productos import Producto as ProductoResource
from .Productos import Productos as ProductosResource
from .Compras import Compra as CompraResource
from .Compras import Compras as ComprasResource
from .ProductosCompras import ProductoCompras as ProductoComprasResource
from .ProductosCompras import ProductosCompra as ProductoCompraResource